### ISSUE TITLE
No funciona con la versión 28 de obs

### ISSUE THREAD

**Issue by GealFox** [malliaridis/obssd#47] opened 2022-12-03 15:41 UTC
# Bug Report

### Environment details
Android Version: 
App Version: 
OBS Studio Version: 
OBS WebSocket Plugin Version: 

Tested devices:

**Comment by malliaridis** [comment] 2022-12-03 16:33
Hey there, the app is only supporting the older OBS version 27.X. I am already working on 2.0 of OBSSD which supports v28 and v29 of OBS Studio as well as Streamlabs OBS.

I decided to start all over again for the new version because the previous architecture was not optimal for supporting multiple OBS tools. That's why it takes much more time to roll out another update.

I gonna close this issue since it is not a bug, but the wished behavior. If you have any question though, feel free to re-open this ticket. :)

**Closed as completed by malliaridis** 2022-12-03 16:33 UTC
Labels: bug
